/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    Card: typeof import('./inertia/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./inertia/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./inertia/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./inertia/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./inertia/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./inertia/components/ui/card/CardTitle.vue')['default']
    Checkbox_group: typeof import('./inertia/components/form/checkbox_group.vue')['default']
    Checkbox_month: typeof import('./inertia/components/form/checkbox_month.vue')['default']
    Error: typeof import('./inertia/components/form/error.vue')['default']
    Footer: typeof import('./inertia/components/footer.vue')['default']
    Header: typeof import('./inertia/components/header.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Input_group: typeof import('./inertia/components/form/input_group.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    Message: typeof import('./inertia/components/message.vue')['default']
    NavigationMenu: typeof import('./inertia/components/ui/navigation-menu/NavigationMenu.vue')['default']
    NavigationMenuContent: typeof import('./inertia/components/ui/navigation-menu/NavigationMenuContent.vue')['default']
    NavigationMenuIndicator: typeof import('./inertia/components/ui/navigation-menu/NavigationMenuIndicator.vue')['default']
    NavigationMenuItem: typeof import('./inertia/components/ui/navigation-menu/NavigationMenuItem.vue')['default']
    NavigationMenuLink: typeof import('./inertia/components/ui/navigation-menu/NavigationMenuLink.vue')['default']
    NavigationMenuList: typeof import('./inertia/components/ui/navigation-menu/NavigationMenuList.vue')['default']
    NavigationMenuTrigger: typeof import('./inertia/components/ui/navigation-menu/NavigationMenuTrigger.vue')['default']
    NavigationMenuViewport: typeof import('./inertia/components/ui/navigation-menu/NavigationMenuViewport.vue')['default']
    Select: typeof import('./inertia/components/form/select.vue')['default']
    Select_group: typeof import('./inertia/components/form/select_group.vue')['default']
    Textarea: typeof import('./inertia/components/form/textarea.vue')['default']
    Textarea_group: typeof import('./inertia/components/form/textarea_group.vue')['default']
    Toast: typeof import('./inertia/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./inertia/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./inertia/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./inertia/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./inertia/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./inertia/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./inertia/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./inertia/components/ui/toast/ToastViewport.vue')['default']
  }
}
